/*
 * Copyright (c) 2026 Jonathan Elliot Peace <jep@alphabetiq.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * brcmfmac firmware and NVRAM blob payload. The actual bytes are
 * generated by CMake from the corresponding files in hal_broadcom
 * (fetched via `west blobs fetch hal_broadcom`) and #include'd here.
 */

const unsigned char brcmfmac_fw[] = {
#include "brcmfmac_fw.inc"
};
const unsigned int brcmfmac_fw_len = sizeof(brcmfmac_fw);

const unsigned char brcmfmac_nvram[] = {
#include "brcmfmac_nvram.inc"
};
const unsigned int brcmfmac_nvram_len = sizeof(brcmfmac_nvram);

/* CLM (regulatory database) blob for trim-on-build firmware images
 * that ship without a built-in CLM. Zero-length when
 * CONFIG_WIFI_BRCMFMAC_CLM_FILE is empty.
 */
const unsigned char brcmfmac_clm[] = {
#include "brcmfmac_clm.inc"
};
const unsigned int brcmfmac_clm_len = sizeof(brcmfmac_clm);
