#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# install-to-sdcard.sh -- drop a Zephyr build onto an already-imaged
# Raspberry Pi OS microSD card so it boots Zephyr instead.
#
# Usage:
#   install-to-sdcard.sh <bootfs-mount-point> <path-to-zephyr.bin>
#
# Example (macOS, after flashing RPi OS Lite 64-bit with Pi Imager):
#   install-to-sdcard.sh /Volumes/bootfs build/zephyr/zephyr.bin
#
# The script:
#   1. Copies zephyr.bin into the boot partition.
#   2. Replaces config.txt with the Zephyr-required boot params,
#      preserving the original as config.txt.orig (only on first run).
#
# All Pi firmware blobs (bootcode.bin, fixup.dat, start.elf) are kept
# untouched.

set -e

BOOTFS="$1"
ZEPHYR_BIN="$2"

usage() {
	cat >&2 <<EOF
Usage: $0 <bootfs-mount-point> <path-to-zephyr.bin>

Example (macOS):
  $0 /Volumes/bootfs build/zephyr/zephyr.bin

Example (Linux):
  $0 /media/\$USER/bootfs build/zephyr/zephyr.bin
EOF
	exit 1
}

if [ -z "$BOOTFS" ] || [ -z "$ZEPHYR_BIN" ]; then
	usage
fi

if [ ! -d "$BOOTFS" ]; then
	echo "error: $BOOTFS is not a directory (is the SD card mounted?)" >&2
	exit 1
fi
if [ ! -f "$ZEPHYR_BIN" ]; then
	echo "error: $ZEPHYR_BIN: file not found" >&2
	exit 1
fi
if [ ! -f "$BOOTFS/bootcode.bin" ] || [ ! -f "$BOOTFS/start.elf" ]; then
	echo "error: $BOOTFS does not look like a Pi boot partition" >&2
	echo "       (no bootcode.bin or start.elf present)" >&2
	exit 1
fi

cp "$ZEPHYR_BIN" "$BOOTFS/zephyr.bin"

if [ -f "$BOOTFS/config.txt" ] && [ ! -f "$BOOTFS/config.txt.orig" ]; then
	cp "$BOOTFS/config.txt" "$BOOTFS/config.txt.orig"
fi

cat > "$BOOTFS/config.txt" <<'EOF'
# Generated by zephyr/boards/raspberrypi/rpi_zero_2w/support/install-to-sdcard.sh.
# The original Raspberry Pi OS config.txt is preserved as config.txt.orig.

arm_64bit=1
core_freq=250

# Route the PL011 (uart0) to GPIO 14/15 by moving Bluetooth onto the
# mini-UART. The PL011 has a 16+6-bit fractional baud divider, far
# more flexible than the mini-UART's integer-only divisor.
enable_uart=1
dtoverlay=disable-bt
# 1 Mbaud lands on an exact integer divisor at the default 48 MHz
# PL011 UART_CLK (IBRD=3, FBRD=0 -> 48 MHz / 16 / 3 = 1 MHz exactly).
# No init_uart_clock override needed. 921600 was tried first but the
# tio/macOS USB-serial adapter on this host produces ~850 kbps when
# asked for 921600; 1 Mbaud is unambiguous on both sides.
init_uart_baud=1000000

kernel_address=0x200000
kernel=zephyr.bin
EOF

echo "Installed $(basename "$ZEPHYR_BIN") to $BOOTFS"
echo "Eject the card and boot the Pi."
