#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# install-to-sdcard.sh -- drop a Zephyr build onto an already-imaged
# Raspberry Pi OS microSD card so it boots Zephyr instead.
#
# Usage:
#   install-to-sdcard.sh <bootfs-mount-point> <path-to-zephyr.bin>
#
# Example (macOS, after flashing RPi OS Lite 64-bit with Pi Imager):
#   install-to-sdcard.sh /Volumes/bootfs build/zephyr/zephyr.bin
#
# The script:
#   1. Copies zephyr.bin into the boot partition.
#   2. Replaces config.txt with the Zephyr-required boot params,
#      preserving the original as config.txt.orig (only on first run).
#
# All Pi firmware blobs (bootcode.bin, fixup.dat, start.elf) are kept
# untouched.

set -e

BOOTFS="$1"
ZEPHYR_BIN="$2"

usage() {
	cat >&2 <<EOF
Usage: $0 <bootfs-mount-point> <path-to-zephyr.bin>

Example (macOS):
  $0 /Volumes/bootfs build/zephyr/zephyr.bin

Example (Linux):
  $0 /media/\$USER/bootfs build/zephyr/zephyr.bin
EOF
	exit 1
}

if [ -z "$BOOTFS" ] || [ -z "$ZEPHYR_BIN" ]; then
	usage
fi

if [ ! -d "$BOOTFS" ]; then
	echo "error: $BOOTFS is not a directory (is the SD card mounted?)" >&2
	exit 1
fi
if [ ! -f "$ZEPHYR_BIN" ]; then
	echo "error: $ZEPHYR_BIN: file not found" >&2
	exit 1
fi
if [ ! -f "$BOOTFS/bootcode.bin" ] || [ ! -f "$BOOTFS/start.elf" ]; then
	echo "error: $BOOTFS does not look like a Pi boot partition" >&2
	echo "       (no bootcode.bin or start.elf present)" >&2
	exit 1
fi

cp "$ZEPHYR_BIN" "$BOOTFS/zephyr.bin"

if [ -f "$BOOTFS/config.txt" ] && [ ! -f "$BOOTFS/config.txt.orig" ]; then
	cp "$BOOTFS/config.txt" "$BOOTFS/config.txt.orig"
fi

cat > "$BOOTFS/config.txt" <<'EOF'
# Generated by zephyr/boards/raspberrypi/rpi_zero_2w/support/install-to-sdcard.sh.
# The original Raspberry Pi OS config.txt is preserved as config.txt.orig.

arm_64bit=1
# enable_uart=1 routes the mini-UART to GPIO 14/15 and locks the core
# clock so its baud divisor stays valid.
enable_uart=1
core_freq=250
kernel_address=0x200000
kernel=zephyr.bin

# Bring HDMI up at boot even if no monitor is attached when the Pi is
# powered on. Without this, hot-plugging a cable later leaves the
# pipeline cold and the Zephyr FB driver's ALLOCATE_BUFFER returns
# an empty buffer. Harmless when HDMI isn't used.
hdmi_force_hotplug=1
EOF

echo "Installed $(basename "$ZEPHYR_BIN") to $BOOTFS"
echo "Eject the card and boot the Pi."
